---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted
    enabled: true

- name: Restart grafana-server
  ansible.builtin.service:
    name: grafana-server
    state: restarted

- name: Update apt cache
  apt:
    update_cache: yes
#    cache_valid_time: 3600


- name: Restart Grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: true
