- name: Create Prometheus user
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    shell: /bin/false
    create_home: false
    system: true

- name: Extract Prometheus tarball
  ansible.builtin.unarchive:
    src: "{{ prometheus_tarball }}"
    dest: /tmp
    remote_src: true

- name: Create Prometheus configuration directory
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0755"

- name: Copy prometheus.yml to config directory
  ansible.builtin.copy:
    src: "{{ prometheus_extract_path }}/prometheus.yml"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0644"

- name: Move Prometheus binaries
  ansible.builtin.copy:
    remote_src: true
    src: "{{ prometheus_extract_path }}/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    mode: "0755"
  loop:
    - prometheus
    - promtool

- name: Create data directory
  ansible.builtin.file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: "0755"

- name: Set ownership for Prometheus config directory
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    recurse: yes
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"

- name: Deploy systemd service file
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"
  notify:
    - Reload systemd
    - Restart Prometheus

- name: Enable and start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started
